project:
  type: website
  output-dir: docs
  resources:
    - CNAME
  render:
    - index.qmd
    - about.qmd
    - Trail_1__Seven_Islands.qmd
    - Trail_20___Honey_Creek.qmd
    - Trail_24__Middle_Prong.qmd
    - a-story-about-a-hike.qmd
    - "AAA - Considerations_for_Your_First_Hike.qmd"
    - "AAA - Finding_a_Hike.qmd"

website:
  title: "Hiking Knoxville"
  page-footer:
    center: "© 2026 Katie and Joshua Rosenberg. All rights reserved."
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - text: "The Book"
        menu:
          - href: a-story-about-a-hike.qmd
            text: "A Story About a Hike"
          - href: "AAA - Considerations_for_Your_First_Hike.qmd"
            text: "Getting Ready for Your First Hike"
          - href: "AAA - Finding_a_Hike.qmd"
            text: "Finding a Hike"
      - text: "Sample Chapters"
        menu:
          - href: Trail_1__Seven_Islands.qmd
            text: "Seven Islands (Trail 1)"
          - href: Trail_20___Honey_Creek.qmd
            text: "Honey Creek (Trail 19)"
          - href: Trail_24__Middle_Prong.qmd
            text: "Middle Prong (Trail 24)"
      - href: about.qmd
        text: About the Authors

format:
  html:
    theme: cosmo
    css: style.css
    toc: false
