project:
  type: book
  output-dir: docs
  resources:
    - CNAME
 
exclude:
    - "*.docx"
    - "*.pdf"
    - "drafts/"        # (if you have a folder of large docs)

copyright:  "© 2025 Katie Rosenberg and Joshua Rosenberg. All rights reserved."
number-depth: 1
number-sections: false
callout-appearance: simple
keep-tex: true

format:
  html:
    theme: cosmo1
    css: style.css
    toc: false
  docx: default
  pdf: default
    
book:
  title: "Little Kids, Big Adventures: A Guide to Family Hikes Around Knoxville"
  subtitle: "The Tennessee Valley, Cumberland Plateau, and Great Smoky Mountains National Park"
  author: "Katie Rosenberg and Joshua Rosenberg"
  date: "February, 2025"
  chapters:
    - part: "Front Matter"
      chapters:   
        - zzz-dedication.qmd
        - ZZZ - Acknowledgments.qmd
        - index.qmd
    - part: "Getting Ready for Your First Hike"
      chapters:
        - a-story-about-a-hike.qmd
    - part: "How to Use This Book"
      chapters:
        - AAA - overview-of-the-hikes.qmd
    - part: Sec - Knoxville.qmd
      chapters: 
        - Trail_1__Seven_Islands.qmd
    - part: Sec - The_Cumberland_Plateau.qmd
      chapters:
        - Trail_13__Emory_Falls.qmd
    - part: Sec - The_Great_Smoky_Mountains_National_Park.qmd
      chapters:
        - Trail_24__Middle_Prong.qmd
    - part: "Doing More"
      chapters:
        - ZZZ - Deepening_the_Experience.qmd
    - part: "End Matter"
      chapters:   
        - ZZZ - About_the_Authors.qmd
        - ZZZ - Appendices.qmd

bibliography: references.bib