project:
  type: website
  output-dir: docs
  resources:
    - CNAME
  render:
    - index.qmd
    - about.qmd
    - Trail_1__Seven_Islands.qmd

website:
  title: "Little Kids, Big Adventures"
  page-footer:
    center: "© 2026 Katie Rosenberg and Joshua Rosenberg. All rights reserved."
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: Trail_1__Seven_Islands.qmd
        text: Sample Chapter
      - href: about.qmd
        text: About the Authors

format:
  html:
    theme: cosmo
    css: style.css
    toc: false
