#  ## Finding a Hike

### “Best hikes” lists may not be the best for families

Many lists of the best hikes around Knoxville (and other areas) exist. These lists feature fantastic hikes: challenging, scenic, and worth visiting. However, these hikes are often very popular, which can lead to congested trails. Furthermore, some of the hikes on lists of the best hikes in an area might not be the best for hiking with _kids_.

Thus, the best family-friend hike around Knoxville may be different from the best hike: who wants to drive for hours, get stuck in traffic, and end up on a too-busy trail — especially with little ones? This leads to the following question, then:

*What’s the best family-friendly hike around Knoxville?*

### The best family-friendly hike is . . . 

In our experience, it can be really hard to predict which when and where we’ll have a great time. Sometimes we have picked out a popular hike, but ended up disappointed by crowds and stressful drives there and back --- other times, we have picked out a trail near downtown Knoxville and a whim and have been delighted. 

Thus, we think the *best family-friendly hike around Knoxville* is where your family has the best experiences. Parents and caregivers know how this works in other places and at other times: kids receive a holiday gift, and they end up playing in the cardboard boxes. The best family-friendly hike is the one where your family feels connected and creates lasting memories—whether it’s a scenic overlook or a creek where your kids throw rocks for hours.

That said, the hikes in this book are those on which we have had good experiences. We think those in this book offer great “bang for your buck”. While some of them are very popular, others are far less well-known. We tried to recommend the hikes that are in the sweet spot for parents of younger children: not too far away, not so challenging so as to be discouraging to kids and their parents; near amenities; and being scenic, challenging, and rewarding. 

### Finding the best hike for your family

Apart from considering the time of the year and the weather (always important!), here are some questions that we think it can be useful to consider before planning a hike:

- **How far do we want to drive?**
- **How much time do we have to hike?**
- **How much of a challenge are our children—and how much of a challenge are we—looking for?**

Answering these questions will help you find trails that are the right distance, length, and difficulty for your family.

Each trail in this book includes the approximate driving distance from Knoxville (XXX - make sure to add when editing the tables), the length of the hike, and for which ages the hike is best. Check those out!

Lastly, if you’re looking for some inspiration, we have created top five lists for different features of trails in the Top 5 Hikes chapter later in this book.

### How to use this book

This book is organized into the three regions we mentioned in the last chapter -- in and around Knoxville, the Cumberland Plateau, and the Great Smoky Mountains National park.

Within each section, we ordered the trails loosely along the lines of those we’d recommend first to friends looking for a pointer for where to go. Thus, the first few hikes in each section are what we think of as sure bets — get the weather right, pack a bunch of snacks, and we think you’ll likely have a good time. For example, Seven Islands in Knoxville is a reliable choice with paved paths, beautiful views, and plenty of spots for kids to explore. The other hikes are also great but may be more challenging or some care with respect to timing to avoid crowds.

Each hike includes a brief overview, key characteristics, a trail description, directions to the trailhead. We also include a map of the trail, and a note about what’s nearby. The trails also include one or more "callouts" to scientific, historical, or other interesting information about the trail.

The trail maps should be pretty straightforward to use; the trailheads are marked with a green dot, and the trail is in red, with key features of the trail noted along the way. There are symbols for parking areas, restrooms, scenic overlooks, waterfalls, and other amenities, like playgrounds and picnic areas.

Now that you know how to choose the perfect trail, let’s dive into tips for planning your first hike with kids in the next chapter.