## Top 5 Hikes

Here are some hikes that we recommend for different reasons--and ages of kids.

### Top 5 - For Hiking With Babies and Infants

1.  High Ground Park
2.  Knox-Blount Greenway
3.  Lakeshore Park
4.  UT Arboretum
5.  Norris Dam

### Top 5 - Real Hikes for Little Explorers Walking on Their Own

1. Ijams Riverside
2. Seven Islands
3. Emory Falls
4. Abrams Creek
5. Chestnut Tops

### Top 5 - Bigger Adventures for Bigger Kids

1.  Alum Cave
2.  Andrews Bald
3.  Honey Creek
4.  Little River
5.  Abrams Falls

### Top 5 - For Kids Who Love to Play in the Water

1. Middle Prong
2. Abrams Creek 
3. Spruce Flats Falls
4. Honey Creek
5. Mouse Creek

### Top 5 - For Kids Who Need a Playground Nearby

1. Lakeshore
2. Emory Fall
3. Ijams Riverside
4. Ijams Crag
5. Sequoyah Park

### Top 5 - Most Scenic

1.  Andrews Bald
2.  Alum Cave
3.  Obed Point
4.  Honey Creek
5.  Abrams Falls

### Top 5 - Simply must-do!

1.  Seven Islands
2.  Little River
3.  Honey Creek
4.  Andrews Bald
5.  Alum Cave