## Top 5 Hikes

Here are some hikes that we recommend for different reasons--and ages of kids.

### For Hiking With Babies and Infants

*These hikes are great when a short distance and a paved path are a priority.*

1.  High Ground Park
2.  Knox-Blount Greenway
3.  Lakeshore Park
4.  UT Arboretum
5.  Norris Dam

### Real Hikes for Little Explorers Walking on Their Own

*These are "real" hikes--you and your little will know it!--but they're also a reasonable distance and with not-too-challenging terrain.*

1. Ijams Riverside
2. Seven Islands
3. Emory Falls
4. Abrams Creek
5. Chestnut Tops

### For Kids Who Need a Playground Nearby

*Who doesn't love a hike that starts and ends at or near a playground?*

1. Lakeshore
2. Emory Fall
3. Ijams Riverside
4. Ijams Crag
5. Sequoyah Park

### For Kids Who Love to Play in the Water

*These hikes are great in warmer weather; bring the right clothing and shoes and let 'em splash!*

1. Middle Prong
2. Abrams Creek 
3. Spruce Flats Falls
4. Honey Creek
5. Mouse Creek

### Best Spots for a Picnic

*Each of these is a fantastic place to have a family picnic.*

1. Mouse Creek
2. Lakeshore
3. Seven Islands
4. Sequoyah Park
5. Ijams Crag

### Bigger Adventures for Bigger Kids

*More challenging hikes for kids who are ready for the next challenge; completing any of these is an achievement.

1.  Alum Cave -
2.  Andrews Bald -
3.  Honey Creek - 
4.  Little River
5.  Abrams Falls