#  ## About this Book

### What this Book is About (and Why We Wrote It)

While we are rooted now, when we moved to Knoxville with a little one -- our little one was only 3 months old -- we (understandably) found it hard to find our place in our new home. Our first trip to Ijams helped us to feel like we knew where to go for a weekend expedition. We added Lakeshore and House Mountain. A camping trip to Frozen Head State Park opened our eyes: this place is special! Later, our first trip to the Smokies sealed the deal: we loved it here. As we transitioned from newcomers to those welcoming new friends, we were increasingly asked a question: 

*Where should we go to hike?*

This book is meant to be our answer -- for our friends and for you. It's also a reflection of our love for the areas around Knoxville, where we have been lucky to have experiences as a family and with our friends that we cherish.

### Who this Book is For

Well, are you looking for family-friendly hikes in or near Knoxville? Then this book is for you! We worked hard to be laser focused on that task. Several great books on hiking in Knoxville or its surroundings exist (we detail some of our favorites in Chapter XX). This book is for families and others caring for children who are looking for an accessible introduction to the outdoors that spares no excitement.

We have been lucky to have watch our oldest child grow from a three-month-old to (at the time of writing) a seven-year-old since we moved to Knoxville, and the hikes we have sought out and enjoyed have -- naturally -- changed over time. Furthermore, from the time we *proposed* this book (in 2022) until when we completed it (in 2025), we welcomed our daughter in 2023, changing the game in terms of what trails we hiked, and when and how we did. 

Thus, we are sensitive to how what counts as a family-friendly hike is likely different at different times -- and what we consider to be family-friendly differs (even between us as co-authors; cough cough, Josh!). For these reasons, we included a wide range of hikes, from those shorter than a mile on paved trails to epic expeditions into the Smokies. In sum, we took care to describe the hikes in ways that will allow you to choose those that are the best for you.

We’ll share a little bit more in Chapter XXX, but we included hikes that are suitable for the youngest of children (infants who are pushed in strollers or carried in child carriers) up through pre-teens, reasoning that plucky teenagers could consult general hiking guides for the most challenging hikes. 

### Where the Hikes Are

All of the hikes are near Knoxville, from just a few minutes to within an hour or two drive (but no longer). In accordance with our focus on hiking with younger children, most of the hikes are within an hour’s drive of Knoxville. We categorize the hikes into three regions:

- **In and around Knoxville**: Hikes within the Knoxville city limits, to those within a 30-minute drive.
- **The Cumberland Plateau**: An often under-appreciated but fantastic region of rock outcroppings and wild rivers to the West and North of Knoxville. The hikes in this book are from around one to two hours from Knoxville, with most being close to one hour.
- **The Great Smoky Mountains National Park**: The most-visited and the most biodiverse national park—right in Knoxville’s backyard. These are mostly around an hour from Knoxville, though a few are closer to two hours.

### When to Go?

A feature of the outdoors around Knoxville is that it is absolutely possible to hike in all seasons — especially with a little care taken with respect to which trails you visit when. Some hikes are very hot in the summer; others are cold in the winter. A benefit of the variety of being close to both the hiking areas in and around Knoxville and those in the Cumberland Plateau and the Great Smoky Mountains National Park—the Smokies—is that you can be choosy about which you visit. Furthermore, you can be picky about when you visit those trails that can get busy (typically, well-known trails in the Smokies), and so we offer guidance about when to visit those trails for which good timing can make a difference between a great family hike and a (literal) traffic jam.
