# Extracted Callouts

## Trail_1__Seven_Islands.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Paw Paw

A native fruit found around Seven Islands. Tastes like a mix of an apple and a banana. Paw Paw flowers are pollinated by beetles and flies.
:::

---

## Trail_1__Seven_Islands.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Eastern Bluebird

While many birds stop over at Seven Islands and areas like that on their migratory routes south (in the fall) and north (in the spring), the Eastern Bluebird is a year-round resident. Bluebirds are obligate cavity nesters - which is why they have experienced such a decline in their population as urban sprawl has increased. Refuges like Seven Islands give them lots of opportunities to find natural cavities to nest in! -MaryRose Weatherton
:::

---

## Trail_2__Ijams_Riverside.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Blue Phlox

Blue Phlox is a native wildflower that blooms in early to mid-spring. These plants provide an important source of early-season nectar for pollinators, like the swallowtail butterfly and other native moths. -MaryRose Weatherton
:::

---

## Trail_4__High_Ground_Park.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Earthworks

Structures formed from shaping rocks and soil, often as part of forts around Knoxville constructed during the Civil War. Surprisingly long-standing. The earthworks here and at the nearby Fort Dickerson include ramparts – small hills or banks that served as defensive walls.
:::

---

## Trail_10__Sharp_s_Ridge.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Lichen

There are three primary types of lichens: Foliose (leaf-like in appearance), Crustose (crusty looking), and Fruiticose (coral-like and bushy). They are abundant in the region and are great bioindicators of air quality! -Amanda Garner
:::

---

## Trail_12__House_Mountain.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Pine Trees (Family)

A group of conifers (trees with needles typically attached in bundles, and seeds in cones that are typically very rigid) that is distinct from Hemlocks, Spruce, and Fir.
:::

---

## Trail_13__Emory_Falls.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Brushy Mountain State Penitentiary

A closed prison near Frozen Head State Park is full of lore due to its remote location. Part of the inspiration for the Barkley Marathons (you'll have to look it up if you haven't heard of it). Now a site of a restaurant and distillery.
:::

---

## Trail_14__Obed_Point.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Bigleaf Magnolia

Has the largest simple leaf (a leaf with one piece) of any tree in North America. In the fall, the leaves look like pages of newspapers scattered on the ground! Common in the Cumberland Plateau (but not in the Smokies).
:::

---

## Trail_18__Angel_Falls.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Angel Falls

Angel Falls is more a rapids than a waterfall, but there’s a history to its name: It was a waterfall until the 1940s, when it was dynamited to make the river more easily navigable by paddlers and boaters. It was only a little successful: the rapids are known as being impassable for all but the most intrepid whitewater paddlers.
:::

---

## Trail_21__Little_River.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Eastern Hemlock
A tree that “feels” like the Smokies - likes shaded groves. Characterized by its needles being arranged in a flat frond. Threatened by an invasive species, the Hemlock Wooly Adelgid. While many trees in the region are affected (look for a white dusty covering of needles), others are not.
:::

---

## Trail_22__Mouse_Creek.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Blue Ridge Two-Lined Salamander

The Great Smoky Mountains has more than 30 species of salamanders – one of the types of species that contributes to and characterizes the incredible biodiversity of the Smokies. The Blue Ridge Two-Lined Salamander is among the most beautiful salamanders, with its yellow-to-orange coloring and stark black stripes.\
- Amanda Garner
:::

---

## Trail_23__Whiteoak_Sink.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Trillium
Native perennial plants with distinctive three-petal flowers that bloom in the spring. These shade-loving plants are often found in the forest understory, where their seeds are dispersed and buried by ants, in a process called myrmecochory. Trillium plants are protected in many places because they are extremely slow-growing. For some species, it can take anywhere from 5-9 years from being planted to their first bloom; a single plant can live up to 25 years! So, next time you see one, make sure you appreciate their beauty with your eyes only.
- MaryRose Weatherton
:::

---

## Trail_24__Middle_Prong.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Brook Trout
The native species of trout in Smokies streams. Speckled and small. Found at high elevations, whereas the Rainbow Trout and Brown Trout were later introduced for fishing.
:::

---

## Trail_28__Abrams_Falls.qmd

::: {.callout-note appearance="default" icon="false"}
A symbol of the wildness of the Smokies—and a very real presence. If you see one, admire their strength, beauty, and intelligence (from a distance!).
:::

---

## Trail_29__Andrews_Bald.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Fraser Fir
You'll feel like you're in a different state or country when you spot these trees atop the Smokies – usually at elevations above 5,500 feet. Note the “Christmas tree smell”! Afflicted by the Balsam Wooly Adelgid and potentially a changing climate around the ridge of the Smokies, including Kuwohi, you’ll note both dead and diseased and healthy specimens. Recent evidence suggests that the Fraser Firs are healthier as a population than 20-30 years ago.
:::

---

## Trail_30__Alum_Cave_Bluffs.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Jordans Red Cheek
These iconic Smokies salamanders are found only in the Smokies! If you are above 2,500 ft, you might just see one of these amazing critters.
- Amanda Garner
:::

---

## Trail_30__Alum_Cave_Bluffs.qmd

::: {.callout-note appearance="simple" icon="true"}
#### Red Spruce
Similar to Fraser Fir, but larger (taller and wider) and found at lower elevations (beginning around 4,000 feet). Majestic. When you see them, you feel like you’re in high and remote mountains.
:::

---

