## Join, Participate, and Give Back

You may wish to join organizations that advocate for outdoors areas, or give back through donating time or money. Here are some ways to do so.

### Join local organizations

Several local organizations advocate for and support the outdoors around Knoxville in critical ways, from maintaining trails

-   *Friends of the Smokies* (https://friendsofthesmokies.org/): Works with the National Park Service to advocate for the Smokies
-   *Smokies Life* (https://smokieslife.org/): Previously the Great Smoky Mountains Association; manages the stores throughout the park; can purchase parking permits for the National Park at those stores or online through their website
-   *Smoky Mountains Hiking Club* (https://www.smhclub.org/): A longstanding hiking club that organizes multiple hikes in every month of the year
-   *Legacy Parks Foundation* (https://legacyparks.org/): Preserves green space, creates trails, and provides access to waterways around Knoxville

### Participate in programs at local outdoors education centers

One way to be part of a community is to participate in programs at local outdoors education centers.

-   *Ijams* (https://www.ijams.org/): A nature center with a variety of programs and events
-   *Great Smoky Mountains Institute at Tremont* (https://gsmit.org/): A nationally-recognized outdoors and environmental education center located within the National Park; has experiential education programs throughout the year for kids and adults

### Give back

You can donate to all of the above, though participating in their programs or purchasing products from them is a great way to support them. You can also give of your time by volunteering.

-   *Ijams* (https://www.ijams.org/volunteer)
-   *The Great Smoky Mountains National Park* (https://www.nps.gov/grsm/getinvolved/volunteer.htm)
-   *The Big South Fork National River and Recreation Area* (https://www.nps.gov/biso/getinvolved/volunteer.htm)

Apart from formally volunteering, you can be a great steward of the trails on which you hike by following the principles of *Leave No Trace* (see the Appendix for more details), and if you can, pick up trash from your favorite trails, and move branches or brush off the trail to make the path for the next little hiker a little better.
