## Recommended Resources

**Other Hiking Guides**

-   Wise, K. (2014). *Hiking trails of the Great Smoky Mountains: Comprehensive guide*. \[Publisher information needed\].

-   Molloy, J. (2015). *Best tent camping: Tennessee: Your car-camping guide to scenic beauty, the sounds of nature, and an escape from civilization* (2nd ed.). Menasha Ridge Press.

-   Molloy, J. (2012). *Explorer's guide 50 hikes on Tennessee's Cumberland Plateau*. Countryman Press.

-   Molloy, J. (2021). *Five-star trails: Knoxville: 40 spectacular hikes in the heart of East Tennessee* (2nd ed.). Menasha Ridge Press.

**History**

-   Brewer, A., & Brewer, C. (1975). *Valley so wild: A folk history*. East Tennessee Historical Society.

-   Bridges, A., Clement, R., & Wise, K. (Eds.). (2019). *The Terra Incognita reader: Early writings from the Great Smoky Mountains*. University of Tennessee Press.

-   Howell, B. J. (2003). *Folklife along the Big South Fork of the Cumberland River*. University of Tennessee Press.

**Science/Natural History**

-   Linzey, D. W. (2008). *A natural history guide to Great Smoky Mountains National Park*. University of Tennessee Press.

**Field Guides**

-   White, P. (2000). *Wildflowers of the Smokies*. Great Smoky Mountains Association.

-   Kemp, S. (1993). *Trees of the Smokies*. Great Smoky Mountains Association.

-   Tilley, S. G., & Huheey, J. E. (2001). *Reptiles and amphibians of the Smokies*. Great Smoky Mountains Association.

**General Advice on Hiking and Going Outdoors with Kids**

-   Aist, J. (2019). *Babes in the woods: Hiking, camping & boating with babies and young children*. The Mountaineers Books.

-   Ross, C. (2018). *The world is our classroom: How one family used nature and travel to shape an extraordinary education*. Skyhorse Publishing.

-   Alexander, K. (2017). *The backpacking with kids handbook: Your down and dirty guide to fun outdoor adventures with your kids*. Independently published.

**For Children**

-   Oswald, P. (2020). *Hike*. Candlewick Press.

-   Davis, J. P., & Blevins, H. (2021). *Outdoor school: Hiking and camping, the definitive interactive nature guide*. Odd dot.
