name: Render Quarto site → docs/

on:
  push:
    branches:
      - master            # run on every push to master
  workflow_dispatch:      # also allow manual trigger

jobs:
  render-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repo with push rights
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # so we can push commits
          fetch-depth: 0             # get full history

      # 2) Install Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # 3) Render your book; outputs go into docs/
      - name: Render site
        run: quarto render

      # 4) Commit & push any changes in docs/
      - name: Commit updated docs
        uses: EndBug/add-and-commit@v9.1.0
        with:
          author_name: github-actions
          author_email: github-actions@users.noreply.github.com
          message: "chore: auto-render Quarto site to docs/"
          add: "docs"
