name: Quarto Publish

on:
  workflow_dispatch:         # manual trigger
  push:
    branches:
      - master               # only run on pushes to master

permissions:
  contents: write            # allow pushing to gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Debug: list repository contents
        run: |
          echo "Working directory: $(pwd)"
          ls -R .

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and publish site
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
