# .github/workflows/publish.yml
name: Quarto Publish

on:
  workflow_dispatch:       # manual trigger if you ever need it
  push:
    branches:
      - master             # run on every push to master

permissions:
  contents: write          # allow pushing to gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and publish site
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages    # ← push the built site to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
